[tool.poetry]
name = "flexwrfinversion"
version = "0.1.0"
description = ""
authors = ["Christopher Lüken-Winkels <christopher.lueken.winkels@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
xarray = "^2024.5.0"
dask = "^2024.5.2"
pyinverse = {git = "git@github.com:christopher-lw/pyinverse.git", branch = "implement-yadav-version"}
tqdm = "^4.66.4"
sparse = "^0.15.4"
distributed = "^2024.11.2"
loguru = "^0.7.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
